CrmWebApp/Models/CompanySalesDaily.cs
namespace CrmWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("CompanySalesDaily")]
    public partial class CompanySalesDaily
    {
        [Display(Name = "公司业务信息ID")]
        public int Id { get; set; }
        [Display(Name = "公司ID")]
        public int CompanyId { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "公司名称")]
        public string CompanyName { get; set; }

        [StringLength(50)]
        [Display(Name = "负责人")]
        public string ManagerName { get; set; }

        [StringLength(50)]
        [Display(Name = "负责人手机")]
        public string ManagerPhone { get; set; }

        [StringLength(50)]
        [Display(Name = "业务类型")]
        public string SalesType { get; set; }

        [StringLength(50)]
        [Display(Name = "录入人")]
        public string CreateUserName { get; set; }
        [Display(Name = "录入时间")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime? CreateTime { get; set; }

        [Column(TypeName = "date")]
        [Display(Name = "业务记录日期")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime? SalesLogDate { get; set; }        
    }
}

CrmWebApp/Models/CompanySalesDailyViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CrmWebApp.Models
{
    public class CompanySalesDailyViewModel
    {
        [Display(Name = "公司业务信息ID")]
        public int Id { get; set; }
        [Display(Name = "公司ID")]
        public int CompanyId { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "公司名称")]
        public string CompanyName { get; set; }

        [StringLength(50)]
        [Display(Name = "负责人")]
        public string ManagerName { get; set; }

        [StringLength(50)]
        [Display(Name = "负责人手机")]
        public string ManagerPhone { get; set; }

        [StringLength(50)]
        [Display(Name = "业务类型")]
        public string SalesType { get; set; }

        [StringLength(50)]
        [Display(Name = "录入人")]
        public string CreateUserName { get; set; }
        [Display(Name = "录入时间")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime? CreateTime { get; set; }

        [Display(Name = "业务记录日期")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime? SalesLogDate { get; set; }

        [Display(Name = "人员投入")]
        public List<CompanySalesDailySalesSource> SalesSourceList { get; set; }

        [Display(Name = "产品销量(张/天)")]
        public List<CompanySalesDailyProductDesp> SalesProductDespList { get; set; }

        [Display(Name = "产品比例%")]
        public List<CompanySalesDailyParam> SalesProductPercentList { get; set; }

        [Display(Name = "营收信息(元)")]
        public List<CompanySalesDailyParam> SalesProfitList { get; set; }
        
        [Display(Name = "资金情况(万)")]
        public List<CompanySalesDailyFund> SalesFundList { get; set; }

        public CompanySalesDailyViewModel() { }

        public CompanySalesDailyViewModel(CompanySalesDaily dailyItem, List<CompanySalesDailySalesSource> salesSources, List<CompanySalesDailyProductDesp> salesProductDesps,
            List<CompanySalesDailyParam> paramList, List<CompanySalesDailyFund> salesFunds)
        {

            this.SalesType = dailyItem.SalesType;
            this.CompanyId = dailyItem.CompanyId;
            this.CompanyName = dailyItem.CompanyName;
            this.CreateTime = dailyItem.CreateTime;
            this.CreateUserName = dailyItem.CreateUserName;
            this.Id = dailyItem.Id;
            this.ManagerName = dailyItem.ManagerName;
            this.ManagerPhone = dailyItem.ManagerPhone;
            this.SalesLogDate = dailyItem.SalesLogDate;

            //人员投入
            this.SalesSourceList = salesSources;
            //资金情况
            this.SalesFundList = salesFunds;
            //产品销量        
            this.SalesProductDespList = salesProductDesps;
            //产品比例
            this.SalesProductPercentList = new List<CompanySalesDailyParam>();
            //营收信息
            this.SalesProfitList = new List<CompanySalesDailyParam>();

            foreach (CompanySalesDailyParam item in paramList)
            {
                switch (item.ParamName)
                {
                    case "产品结构":
                        this.SalesProductPercentList.Add(item);
                        break;
                    case "营收信息":
                        this.SalesProfitList.Add(item);
                        break;
                    default:
                        break;
                }
            }
        }
    }
}

CrmWebApp/Controllers/CompanySalesDailiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CrmWebApp.Models;
using System.Data.SqlClient;
using PagedList;

namespace CrmWebApp.Controllers
{
    public class CompanySalesDailiesController : Controller
    {
        private OtaCrmModel db = new OtaCrmModel();

        // GET: CompanySalesDailies
        [Authorize(Roles = "SalesDirector,OtaSales,AreaManager,Admin")]
        public ActionResult Index(int? companyId, int? page)
        {
            if (companyId.HasValue)
            {
                ViewBag.CompanyId = companyId.Value;
                ViewBag.CompanyName = db.OtaCompany.FirstOrDefault(p => p.Id == companyId.Value).CompanyName;

                var model = from cbd in db.CompanySalesDaily
                            where cbd.CompanyId == companyId.Value
                            orderby cbd.Id descending
                            select cbd;
                int pageSize = 10;
                int pageNumber = (page ?? 1);

                return View(model.ToPagedList(pageNumber, pageSize));
            }

            return View();
        }

        [Authorize(Roles = "SalesDirector,OtaSales,AreaManager,Admin")]
        public ActionResult ShowViewPartial(int id)
        {
            CompanySalesDaily dailyItem = db.CompanySalesDaily.FirstOrDefault(p => p.Id == id);
            var paramList = from p in db.CompanySalesDailyParam
                            where p.CompanySalesDailyId == id
                            select p;

            var salesSources = from p in db.CompanySalesDailySalesSource
                               where p.CompanySalesDailyId == id
                               select p;

            var salesProductDesps = from p in db.CompanySalesDailyProductDesp
                                    where p.CompanySalesDailyId == id
                                    select p;

            var salesFunds = from p in db.CompanySalesDailyFund
                             where p.CompanySalesDailyId == id
                             select p;

            var model = new CompanySalesDailyViewModel(dailyItem, salesSources.ToList(), salesProductDesps.ToList(), paramList.ToList(), salesFunds.ToList());
            return PartialView("_PartialCompanySalesDailyView", model);
        }

        // GET: CompanySalesDailies/Details/5
        [Authorize(Roles = "SalesDirector,OtaSales,AreaManager,Admin")]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanySalesDaily companySalesDaily = await db.CompanySalesDaily.FindAsync(id);
            if (companySalesDaily == null)
            {
                return HttpNotFound();
            }
            return View(companySalesDaily);
        }

        // GET: CompanySalesDailies/Create
        [Authorize(Roles = "SalesDirector,OtaSales,AreaManager,Admin")]
        public ActionResult Create(int? companyId)
        {
            var model = new CompanySalesDaily();
            if (companyId.HasValue)
            {
                model.CompanyId = companyId.Value;
                var company = db.OtaCompany.FirstOrDefault(p => p.Id == companyId.Value);
                if (company != null)
                {
                    model.CompanyName = company.CompanyName;
                }
                model.CreateUserName = User.Identity.Name;
                model.SalesLogDate = DateTime.Today;
                model.CreateTime = DateTime.Now;
                model.ManagerName = ""; //取上一个记录得数据
                model.ManagerPhone = ""; //取上一个记录得数据
                model.SalesType = "";
            }
            ViewData["SalesTypeList"] = GetSalesTypeList("国内");
            return View(model);
        }

        private List<SelectListItem> GetSalesTypeList(string defaultValue)
        {
            var bussinessTypes = from p in db.ParamDict
                                 where p.ParamName == "业务类型"
                                 select p;
            List<SelectListItem> result = new List<SelectListItem>();
            foreach (var item in bussinessTypes)
            {
                SelectListItem selectItem = new SelectListItem();
                selectItem.Value = item.SubItemName;
                selectItem.Text = item.SubItemName;
                if (!string.IsNullOrEmpty(defaultValue) && defaultValue == item.SubItemName)
                {
                    selectItem.Selected = true;
                }
                result.Add(selectItem);
            }
            return result;
        }

        // POST: CompanySalesDailies/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [Authorize(Roles = "SalesDirector,OtaSales,AreaManager,Admin")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,CompanyId,CompanyName,ManagerName,ManagerPhone,SalesType,CreateUserName,CreateTime,SalesLogDate")] CompanySalesDaily companySalesDaily)
        {
            if (ModelState.IsValid)
            {
                db.CompanySalesDaily.Add(companySalesDaily);
                await db.SaveChangesAsync();
                return RedirectToAction("Edit", new { id = companySalesDaily.Id });
            }

            return View(companySalesDaily);
        }

        // GET: CompanySalesDailies/Edit/5
        [Authorize(Roles = "SalesDirector,OtaSales,AreaManager,Admin")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanySalesDaily companySalesDaily = await db.CompanySalesDaily.FindAsync(id);
            if (companySalesDaily == null)
            {
                return HttpNotFound();
            }

            var paramList = from p in db.CompanySalesDailyParam
                            where p.CompanySalesDailyId == id
                            select p;

            var salesSources = from p in db.CompanySalesDailySalesSource
                               where p.CompanySalesDailyId == id
                               select p;

            var salesProductDesps = from p in db.CompanySalesDailyProductDesp
                                    where p.CompanySalesDailyId == id
                                    select p;

            var salesFunds = from p in db.CompanySalesDailyFund
                             where p.CompanySalesDailyId == id
                             select p;

            var model = new CompanySalesDailyViewModel(companySalesDaily, salesSources.ToList(), salesProductDesps.ToList(), paramList.ToList(), salesFunds.ToList());
            //如果没有默认值，就需要赋值默认值
            if (model.SalesSourceList == null || model.SalesSourceList.Count == 0)
            {
                model.SalesSourceList = GetDefaultSalesSource(id.Value);
            }
            if (model.SalesProductDespList == null || model.SalesProductDespList.Count == 0)
            {
                model.SalesProductDespList = GetDefaultSalesProductDesp(id.Value);
            }
            if (model.SalesProductPercentList == null || model.SalesProductPercentList.Count == 0)
            {
                model.SalesProductPercentList = GetDefaultDailyParamList(id.Value, "产品结构");
            }
            if (model.SalesProfitList == null || model.SalesProfitList.Count == 0)
            {
                model.SalesProfitList = GetDefaultDailyParamList(id.Value, "营收信息");
            }
            if (model.SalesFundList == null || model.SalesFundList.Count == 0)
            {
                model.SalesFundList = GetDefaultSalesFundList(id.Value);
            }
            ViewData["SalesTypeList"] = GetSalesTypeList("国内");
            return View(model);
        }

        #region GetDefaultParams
        public List<CompanySalesDailyFund> GetDefaultSalesFundList(int dailyId)
        {
            List<CompanySalesDailyFund> result = new List<CompanySalesDailyFund>();
            var paramDicts = from p in db.ParamDict
                             where p.ParamName == "B2C平台"
                             select p;
            foreach (ParamDict paramDict in paramDicts)
            {
                CompanySalesDailyFund item = new CompanySalesDailyFund();
                item.CompanySalesDailyId = dailyId;
                item.Id = 0;
                item.FreezeFund = 0;
                item.WorkingFund = 0;
                item.NeededFund = 0;
                item.SalesSource = paramDict.SubItemName;

                result.Add(item);
            }
            return result;
        }

        public List<CompanySalesDailyParam> GetDefaultDailyParamList(int dailyId, string paramName)
        {
            List<CompanySalesDailyParam> result = new List<Models.CompanySalesDailyParam>();
            var paramDicts = from p in db.ParamDict
                             where p.ParamName == paramName
                             select p;
            foreach (ParamDict paramDict in paramDicts)
            {
                CompanySalesDailyParam companyBusinessDailyParam = new CompanySalesDailyParam();
                companyBusinessDailyParam.CompanySalesDailyId = dailyId;
                companyBusinessDailyParam.Id = 0;
                companyBusinessDailyParam.ParamName = paramName;
                companyBusinessDailyParam.SubParamItem = paramDict.SubItemName;
                companyBusinessDailyParam.ItemAmount = 0;

                result.Add(companyBusinessDailyParam);
            }
            return result;
        }

        public List<CompanySalesDailyProductDesp> GetDefaultSalesProductDesp(int dailyId)
        {

CrmWebApp/Views/CompanySalesDailies/Create.cshtml
@model CrmWebApp.Models.CompanySalesDaily

@{
    ViewBag.Title = "Create";
}

<div class="row-fluid">
    <div class="span12">
        <ul class="breadcrumb">
            <li>
                <a href="~/Home/Index">主页</a> <span class="divider"></span>
            </li>
            <li>
                <a href="~/OtaCompanies/Index">公司</a> <span class="divider"></span>
            </li>
            <li>
                <a href="~/OtaCompanies/Details?id=@Model.CompanyId">@Model.CompanyName</a><span class="divider"></span>
            </li>
            <li>
                <a href="~/CompanySalesDailies/Index?companyId=@Model.CompanyId">业务</a> <span class="divider"></span>
            </li>
            <li>
                <a href="#">新建</a> <span class="divider"></span>
            </li>
        </ul>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CompanyId)
        @Html.HiddenFor(model => model.CompanyName)
        
        <div class="form-group">
            @Html.LabelFor(model => model.SalesType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SalesType, ViewData["SalesTypeList"] as List<SelectListItem>, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SalesType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ManagerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ManagerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ManagerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ManagerPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ManagerPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ManagerPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SalesLogDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SalesLogDate, new { htmlAttributes = new { @class = "form-control datetimepicker" } })
                @Html.ValidationMessageFor(model => model.SalesLogDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateUserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateUserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreateUserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateTime, new { htmlAttributes = new { @class = "form-control datetimepicker" } })
                @Html.ValidationMessageFor(model => model.CreateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="新建" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("返回列表", "Index", new { companyId = Model.CompanyId })
</div>

<script type="text/javascript">
    $(".datetimepicker").datetimepicker({
        format: "YYYY-MM-DD"
    });
</script>

CrmWebApp/Views/CompanySalesDailies/Delete.cshtml
@model CrmWebApp.Models.CompanySalesDaily

@{
    ViewBag.Title = "Delete";
}

<div class="row-fluid">
    <div class="span12">
        <ul class="breadcrumb">
            <li>
                <a href="~/Home/Index">主页</a> <span class="divider"></span>
            </li>
            <li>
                <a href="~/OtaCompanies/Index">公司</a> <span class="divider"></span>
            </li>
            <li>
                <a href="~/OtaCompanies/Details?id=@Model.CompanyId">@Model.CompanyName</a><span class="divider"></span>
            </li>
            <li>
                <a href="~/CompanySalesDailies/Index?companyId=@Model.CompanyId">业务</a> <span class="divider"></span>
            </li>
            <li>
                <a href="#">删除</a> <span class="divider"></span>
            </li>
        </ul>
    </div>
</div>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CompanyId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ManagerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ManagerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ManagerPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ManagerPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SalesType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SalesType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateUserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateUserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SalesLogDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SalesLogDate)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("返回列表", "Index", new { companyId = Model.CompanyId })
        </div>
    }
</div>

CrmWebApp/Views/CompanySalesDailies/Details.cshtml
@model CrmWebApp.Models.CompanySalesDaily

@{
    ViewBag.Title = "Details";
}

<div class="row-fluid">
    <div class="span12">
        <ul class="breadcrumb">
            <li>
                <a href="~/Home/Index">主页</a> <span class="divider"></span>
            </li>
            <li>
                <a href="~/OtaCompanies/Index">公司</a> <span class="divider"></span>
            </li>
            <li>
                <a href="~/OtaCompanies/Details?id=@Model.CompanyId">@Model.CompanyName</a><span class="divider"></span>
            </li>
            <li>
                <a href="~/CompanySalesDailies/Index?companyId=@Model.CompanyId">业务</a> <span class="divider"></span>
            </li>
            <li>
                <a href="#">详情</a> <span class="divider"></span>
            </li>
        </ul>
    </div>
</div>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CompanyId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ManagerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ManagerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ManagerPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ManagerPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SalesType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SalesType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateUserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateUserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SalesLogDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SalesLogDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("编辑", "Edit", new { id = Model.Id },new { @class="btn btn-default"}) |
    @Html.ActionLink("返回列表", "Index", new { companyId = Model.CompanyId })
</p>

CrmWebApp/Views/CompanySalesDailies/Index.cshtml
@model PagedList.IPagedList<CrmWebApp.Models.CompanySalesDaily>
@using PagedList.Mvc;
@{
    ViewBag.Title = "业务情况-"+ViewBag.CompanyName;
}

<div class="row-fluid">
    <div class="span12">
        <ul class="breadcrumb">
            <li>
                <a href="~/Home/Index">主页</a> <span class="divider"></span>
            </li>
            <li>
                <a href="~/OtaCompanies/Index">公司</a> <span class="divider"></span>
            </li>
            <li>
                <a href="~/OtaCompanies/Details?id=@ViewBag.CompanyId">@ViewBag.CompanyName</a><span class="divider"></span>
            </li>
            <li>
                <a href="#">业务</a> <span class="divider"></span>
            </li>
        </ul>
    </div>
</div>

<p>
    @Html.ActionLink("新建", "Create", "CompanySalesDailies", new { companyId = ViewBag.CompanyId }, new { @class = "btn btn-default" })
</p>
<table class="table">
    <tr>
        <th>
            业务类型
        </th>
        <th>
            业务日期
        </th>
        <th>
            主管
        </th>
        <th>
            主管电话
        </th>        
        <th>
            录入人
        </th>
        <th>
            录入时间
        </th>        
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SalesType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SalesLogDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ManagerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ManagerPhone)
            </td>            
            <td>
                @Html.DisplayFor(modelItem => item.CreateUserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreateTime)
            </td>            
            <td>
                <a href="#" class="btn btn-default" data-toggle="modal" data-target="#modalDiv" onclick="ShowModalDiv('@item.Id')">查看</a>
                @Html.ActionLink("修改", "Edit", new { id = item.Id }, new { @class = "btn btn-default" })
                @Html.ActionLink("删除", "Delete", new { id = item.Id }, new {  @class = "btn btn-default" })
            </td>
        </tr>
    }

</table>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, companyId = ViewBag.CompanyId }))

<div class="modal" id="modalDiv" tabindex="-1" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <a href="#" class="close" data-dismiss="modal">&times;</a>
            </div>
            <div class="modal-body" id="modalBodyDiv">
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-default" data-dismiss="modal">关闭</a>
            </div>
        </div>
    </div>
</div>

<script>

    var ShowModalDiv = function (modelParam) {
        var serverUrl = "@Url.Content("~/")";
        var url = serverUrl + "CompanySalesDailies/ShowViewPartial?id=" + modelParam;
        $("#modalBodyDiv").load(url, function () {
            $("#modalDiv").modal("show");
        })
    }
</script>