CrmWebApp/Models/CompanyMeeting.cs
namespace CrmWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("CompanyMeeting")]
    public partial class CompanyMeeting
    {
        [Display(Name = "拜访记录ID")]
        public int Id { get; set; }
        [Display(Name = "公司ID")]
        public int CompanyId { get; set; }

        [Required]
        [StringLength(128)]
        [Display(Name = "公司名称")]
        public string CompanyName { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "沟通方式")]
        public string MeetingType { get; set; }

        [Column(TypeName = "date")]
        [Display(Name = "沟通日期")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime MeetDate { get; set; }

        [StringLength(128)]
        [Display(Name = "会面地址")]
        public string MeetAddress { get; set; }

        [StringLength(128)]
        [Display(Name = "拜访人")]
        public string MeetNames { get; set; }

        [StringLength(1024)]
        [Display(Name = "纪要")]
        public string MeetSummary { get; set; }

        [StringLength(50)]
        [Display(Name = "录入人")]
        public string CreateUserName { get; set; }

        [Display(Name = "录入时间")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime? CreateTime { get; set; }
    }
}

CrmWebApp/Models/CompanyMeetingViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CrmWebApp.Models
{
    public class CompanyMeetingViewModel
    {

        [Display(Name = "拜访记录ID")]
        public int Id { get; set; }
        [Display(Name = "公司ID")]
        public int CompanyId { get; set; }

        [Required]
        [StringLength(128)]
        [Display(Name = "公司名称")]
        public string CompanyName { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "沟通方式")]
        public string MeetingType { get; set; }
        
        [Display(Name = "沟通日期")]
        public DateTime MeetDate { get; set; }

        [StringLength(128)]
        [Display(Name = "会面地址")]
        public string MeetAddress { get; set; }

        [StringLength(128)]
        [Display(Name = "拜访人")]
        public string MeetNames { get; set; }

        [StringLength(512)]
        [Display(Name = "纪要")]
        public string MeetSummary { get; set; }

        [StringLength(50)]
        [Display(Name = "录入人")]
        public string CreateUserName { get; set; }

        [Display(Name = "录入时间")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime? CreateTime { get; set; }

        [Display(Name ="沟通记录")]
        public List<CompanyMeetingSubject> MeetingSubjectList { get; set; }

        [Display(Name ="附件")]
        public List<CompanyMedia> MediaList { get; set; }

        public CompanyMeetingViewModel() {  }

        public CompanyMeetingViewModel(CompanyMeeting item,List<CompanyMeetingSubject> meetingSubjects,List<CompanyMedia> mediaList)
        {
            this.CompanyId = item.CompanyId;
            this.CompanyName = item.CompanyName;
            this.CreateTime = item.CreateTime;
            this.CreateUserName = item.CreateUserName;
            this.Id = item.Id;
            this.MeetAddress = item.MeetAddress;
            this.MeetDate = item.MeetDate;
            this.MeetingType = item.MeetingType;
            this.MeetNames = item.MeetNames;
            this.MeetSummary = item.MeetSummary;
            
            this.MeetingSubjectList = meetingSubjects;
            this.MediaList = mediaList;
        }
    }
}

CrmWebApp/Controllers/CompanyMeetingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CrmWebApp.Models;
using System.Data.SqlClient;
using PagedList;

namespace CrmWebApp.Controllers
{
    public class CompanyMeetingsController : Controller
    {
        private OtaCrmModel db = new OtaCrmModel();

        // GET: CompanyMeetings
        [Authorize(Roles = "SalesDirector,OtaSales,AreaManager,Admin")]
        public ActionResult Index(int? companyId, int? page)
        {
            var model = from cbd in db.CompanyMeeting
                        select cbd;
            //orderby cbd.Id descending
            if (companyId.HasValue)
            {
                ViewBag.CompanyId = companyId.Value;
                ViewBag.CompanyName = db.OtaCompany.FirstOrDefault(p => p.Id == companyId.Value).CompanyName;
                model = model.Where(p => p.CompanyId == companyId.Value);
            }
            else
            {
                if (!User.IsInRole("SalesDirector") && !User.IsInRole("Admin"))
                {
                    if (User.IsInRole("AreaManager"))
                    {
                        //找出本区域的所有人，并把它作为条件加入查询结果中
                        ServeAreasController sac = new ServeAreasController();
                        List<string> myAreaUserNameList = sac.GetMyAreaUserNames(User.Identity.Name);
                        model = model.Where(p => myAreaUserNameList.Contains(p.CreateUserName));
                    }
                    else if (User.IsInRole("OtaSales"))
                    {
                        //销售只能看到本人的                    
                        model = model.Where(p => p.CreateUserName == User.Identity.Name);
                    }
                }
            }
            model = model.OrderByDescending(p => p.Id);

            int pageSize = 10;
            int pageNumber = (page ?? 1);

            return View(model.ToPagedList(pageNumber, pageSize));
        }

        [Authorize(Roles = "SalesDirector,OtaSales,AreaManager,Admin")]
        public ActionResult ShowViewPartial(int id)
        {
            CompanyMeeting dailyItem = db.CompanyMeeting.FirstOrDefault(p => p.Id == id);
            var subjectList = from p in db.CompanyMeetingSubject
                              where p.CompanyMeetingId == id
                              select p;
            var mediaList = from p in db.CompanyMedia
                            where p.OuterKeyId == id && p.MediaFor == "拜访记录"
                            select p;

            var model = new CompanyMeetingViewModel(dailyItem, subjectList.ToList(), mediaList.ToList());
            return PartialView("_PartialCompanyMeetingView", model);
        }

        // GET: CompanyMeetings/Details/5
        [Authorize(Roles = "SalesDirector,OtaSales,AreaManager,Admin")]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyMeeting companyMeeting = await db.CompanyMeeting.FindAsync(id);
            if (companyMeeting == null)
            {
                return HttpNotFound();
            }
            return View(companyMeeting);
        }

        // GET: CompanyMeetings/Create
        [Authorize(Roles = "SalesDirector,OtaSales,AreaManager,Admin")]
        public ActionResult Create(int? companyId)
        {
            var model = new CompanyMeeting();
            if (companyId.HasValue)
            {
                model.CompanyId = companyId.Value;
                var company = db.OtaCompany.FirstOrDefault(p => p.Id == companyId.Value);
                if (company != null)
                {
                    model.CompanyName = company.CompanyName;
                }
                model.CreateUserName = User.Identity.Name;
                model.MeetDate = DateTime.Today;
                model.CreateTime = DateTime.Now;
                model.MeetAddress = ""; //取上一个记录得数据
                model.MeetingType = ""; //取上一个记录得数据
                model.MeetNames = ""; //取上一个记录得数据
                model.MeetSummary = "";
            }
            ViewData["MeetingTypeList"] = GetMeetingTypeList("上门拜访");
            return View(model);
        }
        private List<SelectListItem> GetMeetingTypeList(string defaultValue)
        {
            var bussinessTypes = from p in db.ParamDict
                                 where p.ParamName == "沟通方式"
                                 select p;
            List<SelectListItem> result = new List<SelectListItem>();
            foreach (var item in bussinessTypes)
            {
                SelectListItem selectItem = new SelectListItem();
                selectItem.Value = item.SubItemName;
                selectItem.Text = item.SubItemName;
                if (!string.IsNullOrEmpty(defaultValue) && defaultValue == item.SubItemName)
                {
                    selectItem.Selected = true;
                }
                result.Add(selectItem);
            }
            return result;
        }

        // POST: CompanyMeetings/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [Authorize(Roles = "SalesDirector,OtaSales,AreaManager,Admin")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CompanyMeeting companyMeeting)
        {
            ViewData["MeetingTypeList"] = GetMeetingTypeList("上门拜访");
            if (ModelState.IsValid)
            {
                //更新公司的lastupdatedate
                var company = db.OtaCompany.FirstOrDefault(p => p.Id == companyMeeting.CompanyId);
                company.LastMeetingDate = DateTime.Now;
                db.SaveChanges();

                db.CompanyMeeting.Add(companyMeeting);
                await db.SaveChangesAsync();

                return RedirectToAction("Edit", new { Id = companyMeeting.Id });
            }
            return View(companyMeeting);
        }

        // GET: CompanyMeetings/Edit/5
        [Authorize(Roles = "SalesDirector,OtaSales,AreaManager,Admin")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyMeeting companyMeeting = await db.CompanyMeeting.FindAsync(id);
            if (companyMeeting == null)
            {
                return HttpNotFound();
            }
            var meetingSubjects = from p in db.CompanyMeetingSubject
                                  where p.CompanyMeetingId == id.Value
                                  select p;
            var mediaList = from p in db.CompanyMedia
                            where p.OuterKeyId == id.Value && p.MediaFor == "拜访记录"
                            select p;
            var model = new CompanyMeetingViewModel(companyMeeting, meetingSubjects.ToList(), mediaList.ToList());
            ViewData["MeetingTypeList"] = GetMeetingTypeList("上门拜访");
            return View(model);
        }

        // POST: CompanyMeetings/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [Authorize(Roles = "SalesDirector,OtaSales,AreaManager,Admin")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(CompanyMeetingViewModel model, List<CompanyMeetingSubject> meetingSubjectList)
        {
            CompanyMeeting companyMeeting = db.CompanyMeeting.FirstOrDefault(p => p.Id == model.Id);
            companyMeeting.MeetAddress = model.MeetAddress;
            companyMeeting.MeetDate = model.MeetDate;
            companyMeeting.MeetingType = model.MeetingType;
            companyMeeting.MeetNames = model.MeetNames;
            companyMeeting.MeetSummary = model.MeetSummary;
            await db.SaveChangesAsync();

            if (meetingSubjectList != null && meetingSubjectList.Count > 0)
            {
                //保存子项目
                string sql = "Delete From CompanyMeetingSubject Where CompanyMeetingId=@CompanyMeetingId";
                SqlParameter[] paras = new SqlParameter[] {
                     new SqlParameter("@CompanyMeetingId",model.Id)
                    };
                db.Database.ExecuteSqlCommand(sql, paras);
                foreach (CompanyMeetingSubject item in meetingSubjectList)
                {
                    if (!string.IsNullOrEmpty(item.Subject))
                    {
                        db.CompanyMeetingSubject.Add(item);
                    }
                }

                db.SaveChanges();
            }

            return RedirectToAction("Index", new { companyId = model.CompanyId });
        }

        // GET: CompanyMeetings/Delete/5
        [Authorize(Roles = "SalesDirector,OtaSales,AreaManager,Admin")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyMeeting companyMeeting = await db.CompanyMeeting.FindAsync(id);
            if (companyMeeting == null)
            {
                return HttpNotFound();
            }
            return View(companyMeeting);
        }

        // POST: CompanyMeetings/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "SalesDirector,OtaSales,AreaManager,Admin")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            CompanyMeeting companyMeeting = await db.CompanyMeeting.FindAsync(id);
            db.CompanyMeeting.Remove(companyMeeting);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

CrmWebApp/Views/CompanyMeetings/Create.cshtml
@model CrmWebApp.Models.CompanyMeeting

@{
    ViewBag.Title = "Create";
}

<div class="row-fluid">
    <div class="span12">
        <ul class="breadcrumb">
            <li>
                <a href="~/Home/Index">主页</a> <span class="divider"></span>
            </li>
            <li>
                <a href="~/OtaCompanies/Index">公司</a> <span class="divider"></span>
            </li>
            <li>
                <a href="~/OtaCompanies/Details?id=@Model.CompanyId">@Model.CompanyName</a><span class="divider"></span>
            </li>
            <li>
                <a href="~/CompanyMeetings/Index?companyId=@Model.CompanyId">拜访</a> <span class="divider"></span>
            </li>
            <li class="active">
                <a href="#">新建</a> <span class="divider"></span>
            </li>
        </ul>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model=>model.Id)
        @Html.HiddenFor(model => model.CompanyId)
        @Html.HiddenFor(model => model.CompanyName)
        
        <div class="form-group">
            @Html.LabelFor(model => model.MeetingType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.MeetingType, ViewData["MeetingTypeList"] as List<SelectListItem>, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MeetingType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MeetDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MeetDate, new { htmlAttributes = new { @class = "form-control datetimepicker" } })
                @Html.ValidationMessageFor(model => model.MeetDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MeetAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MeetAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MeetAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MeetNames, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MeetNames, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MeetNames, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MeetSummary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.MeetSummary,7,40, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MeetSummary, "最大长度1000汉字", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateUserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateUserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreateUserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateTime, new { htmlAttributes = new { @class = "form-control datetimepicker" } })
                @Html.ValidationMessageFor(model => model.CreateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="新建" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("返回列表", "Index", new { companyId = Model.CompanyId })
</div>

<script type="text/javascript">
    $(".datetimepicker").datetimepicker({
        format: "YYYY-MM-DD"
    });
</script>

CrmWebApp/Views/CompanyMeetings/Delete.cshtml
@model CrmWebApp.Models.CompanyMeeting

@{
    ViewBag.Title = "Delete";
}

<div class="row-fluid">
    <div class="span12">
        <ul class="breadcrumb">
            <li>
                <a href="~/Home/Index">主页</a> <span class="divider"></span>
            </li>
            <li>
                <a href="~/OtaCompanies/Index">公司</a> <span class="divider"></span>
            </li>
            <li>
                <a href="~/OtaCompanies/Details?id=@Model.CompanyId">@Model.CompanyName</a><span class="divider"></span>
            </li>
            <li>
                <a href="~/CompanyMeetings/Index?companyId=@Model.CompanyId">拜访</a> <span class="divider"></span>
            </li>
            <li class="active">
                <a href="#">删除</a> <span class="divider"></span>
            </li>
        </ul>
    </div>
</div>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CompanyId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MeetingType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MeetingType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MeetDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MeetDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MeetAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MeetAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MeetNames)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MeetNames)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MeetSummary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MeetSummary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateUserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateUserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateTime)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("返回列表", "Index", new { companyId = Model.CompanyId })
        </div>
    }
</div>

CrmWebApp/Views/CompanyMeetings/Details.cshtml
@model CrmWebApp.Models.CompanyMeeting

@{
    ViewBag.Title = "Details";
}

<div class="row-fluid">
    <div class="span12">
        <ul class="breadcrumb">
            <li>
                <a href="~/Home/Index">主页</a> <span class="divider"></span>
            </li>
            <li>
                <a href="~/OtaCompanies/Index">公司</a> <span class="divider"></span>
            </li>
            <li>
                <a href="~/OtaCompanies/Details?id=@Model.CompanyId">@Model.CompanyName</a><span class="divider"></span>
            </li>
            <li>
                <a href="~/CompanyMeetings/Index?companyId=@Model.CompanyId">拜访</a> <span class="divider"></span>
            </li>
            <li class="active">
                <a href="#">详情</a> <span class="divider"></span>
            </li>
        </ul>
    </div>
</div>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CompanyId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MeetingType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MeetingType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MeetDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MeetDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MeetAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MeetAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MeetNames)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MeetNames)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MeetSummary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MeetSummary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateUserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateUserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateTime)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("编辑", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("返回列表", "Index", new { companyId = Model.CompanyId })
</p>

CrmWebApp/Views/CompanyMeetings/Index.cshtml
@model PagedList.IPagedList<CrmWebApp.Models.CompanyMeeting>
@using PagedList.Mvc;
@{
    ViewBag.Title = "沟通记录-" + ViewBag.CompanyName;
}

<div class="row-fluid">
    <div class="span12">
        <ul class="breadcrumb">
            <li>
                <a href="~/Home/Index">主页</a> <span class="divider"></span>
            </li>
            <li>
                <a href="~/OtaCompanies/Index">公司</a> <span class="divider"></span>
            </li>
            <li>
                <a href="~/OtaCompanies/Details?id=@ViewBag.CompanyId">@ViewBag.CompanyName</a><span class="divider"></span>
            </li>
            <li class="active">
                <a href="#">拜访</a> <span class="divider"></span>
            </li>
        </ul>
    </div>
</div>

<p>
    @Html.ActionLink("新建", "Create", "CompanyMeetings", new { companyId = ViewBag.CompanyId }, new { @class = "btn btn-default" })
</p>
<table class="table">
    <tr>
        <th>
            方式
        </th>
        <th>
            日期
        </th>
        <th>
            地址
        </th>
        <th>
            沟通人
        </th>
        <th>
            录入人
        </th>
        <th>
            录入时间
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MeetingType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MeetDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MeetAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MeetNames)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreateUserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreateTime)
            </td>
            <td>
                <a href="#" class="btn btn-default" data-toggle="modal" data-target="#modalDiv" onclick="ShowModalDiv('@item.Id')">查看</a>
                @Html.ActionLink("编辑", "Edit", new { id = item.Id }, new { @class = "btn btn-default" })
                @Html.ActionLink("删除", "Delete", new { id = item.Id }, new { @class = "btn btn-default" })
            </td>
        </tr>
    }

</table>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, companyId = ViewBag.CompanyId }))

<div class="modal" id="modalDiv" tabindex="-1" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <a href="#" class="close" data-dismiss="modal">&times;</a>
            </div>
            <div class="modal-body" id="modalBodyDiv">
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-default" data-dismiss="modal">关闭</a>
            </div>
        </div>
    </div>
</div>

<script>

    var ShowModalDiv = function (modelParam) {
        var serverUrl = "@Url.Content("~/")";
        var url = serverUrl + "CompanyMeetings/ShowViewPartial?id=" + modelParam;
        $("#modalBodyDiv").load(url, function () {
            $("#modalDiv").modal("show");
        })
    }
</script>