CrmWebApp/Models/CompanyCertificate.cs
namespace CrmWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("CompanyCertificate")]
    public partial class CompanyCertificate
    {
        public int Id { get; set; }
        [Display(Name = "公司ID")]
        public int CompanyId { get; set; }

        [StringLength(50)]
        [Display(Name = "资质名称")]
        public string CertificateName { get; set; }

        [StringLength(128)]
        [Display(Name = "公司名")]
        public string CompanyName { get; set; }

        [StringLength(50)]
        [Display(Name = "图片网址")]
        public string PictureUrl { get; set; }
        [Display(Name = "录入时间")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime? CreateTime { get; set; }

        [StringLength(50)]
        [Display(Name = "录入人")]
        public string CreateUserName { get; set; }
    }
}

CrmWebApp/Controllers/CompanyCertificatesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CrmWebApp.Models;
using System.IO;

namespace CrmWebApp.Controllers
{
    public class CompanyCertificatesController : Controller
    {
        private OtaCrmModel db = new OtaCrmModel();

        // GET: CompanyCertificates
        [Authorize(Roles = "SalesDirector,OtaSales,AreaManager,Admin")]
        public async Task<ActionResult> Index(int? companyId)
        {
            var model = from cbd in db.CompanyCertificate
                        select cbd;
            if (companyId.HasValue)
            {
                model = model.Where(p => p.CompanyId == companyId.Value);
                ViewBag.CompanyId = companyId.Value;
                ViewBag.CompanyName = db.OtaCompany.FirstOrDefault(p => p.Id == companyId.Value).CompanyName;
            }

            return View(await model.ToListAsync());
        }

        // GET: CompanyCertificates/Details/5
        [Authorize(Roles = "SalesDirector,OtaSales,AreaManager,Admin")]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyCertificate companyCertificate = await db.CompanyCertificate.FindAsync(id);
            if (companyCertificate == null)
            {
                return HttpNotFound();
            }
            return View(companyCertificate);
        }

        // GET: CompanyCertificates/Create
        [Authorize(Roles = "SalesDirector,OtaSales,AreaManager,Admin")]
        public ActionResult Create(int? companyId)
        {
            var model = new CompanyCertificate();
            if (companyId.HasValue)
            {
                model.CompanyId = companyId.Value;
                var company = db.OtaCompany.FirstOrDefault(p => p.Id == companyId.Value);
                if (company != null)
                {
                    model.CompanyName = company.CompanyName;
                }
                model.CreateUserName = User.Identity.Name;
                model.CertificateName = "";
                model.CreateTime = DateTime.Now;
                model.PictureUrl = ""; //取上一个记录得数据
            }
            ViewData["CertificateNameList"] = GetCertificateNameList("营业执照");

            return PartialView("_PartialCertificateUpload",model);
        }

        private List<SelectListItem> GetCertificateNameList(string defaultValue)
        {
            var bussinessTypes = from p in db.ParamDict
                                 where p.ParamName == "资质"
                                 select p;
            List<SelectListItem> result = new List<SelectListItem>();
            foreach (var item in bussinessTypes)
            {
                SelectListItem selectItem = new SelectListItem();
                selectItem.Value = item.SubItemName;
                selectItem.Text = item.SubItemName;
                if (!string.IsNullOrEmpty(defaultValue) && defaultValue == item.SubItemName)
                {
                    selectItem.Selected = true;
                }
                result.Add(selectItem);
            }
            return result;
        }

        private bool CreateFolderIfNeeded(string path)
        {
            bool result = true;
            if (!Directory.Exists(path))
            {
                try
                {
                    Directory.CreateDirectory(path);
                }
                catch (Exception)
                {
                    /*TODO: You must process this exception.*/
                    result = false;
                }
            }
            return result;
        }

        // POST: CompanyCertificates/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [Authorize(Roles = "SalesDirector,OtaSales,AreaManager,Admin")]
        public ActionResult Create([Bind(Include = "Id,CompanyId,CertificateName,CompanyName,PictureUrl,CreateTime,CreateUserName")] CompanyCertificate companyCertificate, HttpPostedFileBase imageFile)
        {
            if (ModelState.IsValid)
            {
                //上传图片先
                string pathForSaving = Server.MapPath("~/CompanyImages/Certificates/" + companyCertificate.CompanyName);
                if (this.CreateFolderIfNeeded(pathForSaving))
                {
                    try
                    {
                        string fileName = companyCertificate.CompanyName + "_" + companyCertificate.CertificateName + "_" + DateTime.Now.ToString("yyyyMMddHHmmss");
                        string fileExtension = Path.GetExtension(imageFile.FileName);
                        imageFile.SaveAs(Path.Combine(pathForSaving, fileName + fileExtension));
                        companyCertificate.PictureUrl = fileName + fileExtension;   //保存图片名
                        db.CompanyCertificate.Add(companyCertificate);
                        db.SaveChanges();
                    }
                    catch (Exception ex)
                    {
                        ViewBag.ErrorMessage = string.Format("File upload failed: {0}", ex.Message);
                    }
                }

                return RedirectToAction("Index", new { companyId = companyCertificate.CompanyId });
            }
            ViewData["CertificateNameList"] = GetCertificateNameList("营业执照");

            return View(companyCertificate);
        }

        // GET: CompanyCertificates/Edit/5
        [Authorize(Roles = "SalesDirector,OtaSales,AreaManager,Admin")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyCertificate companyCertificate = await db.CompanyCertificate.FindAsync(id);
            if (companyCertificate == null)
            {
                return HttpNotFound();
            }
            return View(companyCertificate);
        }

        // POST: CompanyCertificates/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [Authorize(Roles = "SalesDirector,OtaSales,AreaManager,Admin")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,CompanyId,CertificateName,CompanyName,PictureUrl,CreateTime,CreateUserName")] CompanyCertificate companyCertificate)
        {
            if (ModelState.IsValid)
            {
                db.Entry(companyCertificate).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(companyCertificate);
        }

        // GET: CompanyCertificates/Delete/5
        [Authorize(Roles = "SalesDirector,OtaSales,AreaManager,Admin")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyCertificate companyCertificate = await db.CompanyCertificate.FindAsync(id);
            if (companyCertificate == null)
            {
                return HttpNotFound();
            }
            return View(companyCertificate);
        }

        // POST: CompanyCertificates/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "SalesDirector,OtaSales,AreaManager,Admin")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            CompanyCertificate companyCertificate = await db.CompanyCertificate.FindAsync(id);
            int companyId = companyCertificate.CompanyId;
            db.CompanyCertificate.Remove(companyCertificate);
            await db.SaveChangesAsync();
            return RedirectToAction("Index",new { companyId=companyId});
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CrmWebApp/Views/CompanyCertificates/Create.cshtml
@model CrmWebApp.Models.CompanyCertificate

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "CompanyCertificates", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>@ViewBag.CompanyName</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CertificateName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CertificateName, ViewData["CertificateNameList"] as List<SelectListItem>, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CertificateName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CompanyId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateUserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateUserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreateUserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">图片上传</label>
            <div class="col-md-10">
                <div>
                    <input id="imageFile" type="file" name="imageFile" class="form-control file-loading" accept="image/*">
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script>
    $("#imageFile").fileinput({
        language: 'zh', //设置语言
        uploadUrl: '/CompanyCertificates/Create', //上传的地址
        allowedFileExtensions: ['jpg', 'png', 'gif'],//接收的文件后缀
        showUpload: true, //是否显示上传按钮
        showCaption: false,//是否显示标题
        showPreview: true,
        browseClass: "btn btn-primary", //按钮样式
        previewFileType: 'image',
        enctype: 'multipart/form-data',
        validateInitialCount: true,
        previewFileIcon: "<i class='glyphicon glyphicon-king'></i>",
    })


</script>

CrmWebApp/Views/CompanyCertificates/Delete.cshtml
@model CrmWebApp.Models.CompanyCertificate

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CompanyCertificate</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CompanyId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CertificateName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CertificateName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PictureUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PictureUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateUserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateUserName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CrmWebApp/Views/CompanyCertificates/Details.cshtml
@model CrmWebApp.Models.CompanyCertificate

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>CompanyCertificate</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CompanyId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CertificateName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CertificateName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PictureUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PictureUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateUserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateUserName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CrmWebApp/Views/CompanyCertificates/Edit.cshtml
@model CrmWebApp.Models.CompanyCertificate

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CompanyCertificate</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CompanyId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CertificateName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CertificateName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CertificateName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PictureUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PictureUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PictureUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateUserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateUserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreateUserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CrmWebApp/Views/CompanyCertificates/Index.cshtml
@model IEnumerable<CrmWebApp.Models.CompanyCertificate>

@{
    ViewBag.Title = "Index";
}

<div class="row-fluid">
    <div class="span12">
        <ul class="breadcrumb">
            <li>
                <a href="~/Home/Index">主页</a> <span class="divider"></span>
            </li>
            <li>
                <a href="~/OtaCompanies/Index">公司</a> <span class="divider"></span>
            </li>
            <li>
                <a href="#">资质</a> <span class="divider"></span>
            </li>
            <li class="active">
                <a href="#">@ViewBag.CompanyName</a> <span class="divider"></span>
            </li>
        </ul>
    </div>
</div>

<p>
    <a href="#" class="btn btn-default" data-toggle="modal" data-target="#modalDiv" onclick="ShowModal('@ViewBag.CompanyId')">新增</a>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CertificateName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PictureUrl)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreateTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreateUserName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        var imageUrl = @Url.Content("~/CompanyImages/Certificates/" + item.CompanyName + "/" + item.PictureUrl);
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CertificateName)
            </td>
            <td>
                <a href="@imageUrl" class="thumbnail" style="width:100px;" target="_blank">
                    <img src="@imageUrl" style="height:100px;width:100px;display: block" />
                </a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreateUserName)
            </td>
            <td>
                @Html.ActionLink("删除", "Delete", new { id = item.Id }, new { @class = "btn btn-default" })
            </td>
        </tr>
    }

</table>

<div class="modal" id="modalDiv" tabindex="-1" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <a href="#" class="close" data-dismiss="modal">&times;</a>
            </div>
            <div class="modal-body" id="modalBodyDiv">

            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-default" data-dismiss="modal">关闭</a>
            </div>
        </div>
    </div>
</div>

<script>

    var ShowModal = function (paramValue) {
        var serverUrl = "@Url.Content("~/")";
        var url = serverUrl + "CompanyCertificates/Create?companyId=" + paramValue;
        $("#modalBodyDiv").load(url, function () {
            $("#modalDiv").modal("show");
        })
    }
</script>