CrmWebApp/Models/CompanyBusinessDaily.cs
namespace CrmWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("CompanyBusinessDaily")]
    public partial class CompanyBusinessDaily
    {
        public int Id { get; set; }
        [Display(Name ="公司ID")]
        public int CompanyId { get; set; }

        [StringLength(50)]
        [Display(Name ="公司名")]
        public string CompanyName { get; set; }

        [StringLength(50)]
        [Display(Name ="业务类型")]
        public string BussinessType { get; set; }

        [StringLength(50)]
        [Display(Name ="运营负责人")]
        public string ManagerName { get; set; }

        [StringLength(50)]
        [Display(Name ="录入人")]
        public string CreateUserName { get; set; }

        [Display(Name ="录入时间")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime? CreateTime { get; set; }

        [Column(TypeName = "date")]
        [Display(Name ="运营状况日期")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime? BussinessLogDate { get; set; }
    }
}

CrmWebApp/Models/CompanyBusinessDailyViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CrmWebApp.Models
{
    public class CompanyBusinessDailyViewModel
    {
        public int Id { get; set; }
        [Display(Name = "公司ID")]
        public int CompanyId { get; set; }

        [StringLength(50)]
        [Display(Name = "公司名")]
        public string CompanyName { get; set; }

        [StringLength(50)]
        [Display(Name = "业务类型")]
        public string BussinessType { get; set; }

        [StringLength(50)]
        [Display(Name = "运营负责人")]
        public string ManagerName { get; set; }

        [StringLength(50)]
        [Display(Name = "录入人")]
        public string CreateUserName { get; set; }

        [Display(Name = "录入时间")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime? CreateTime { get; set; }
        
        [Display(Name = "运营状况日期")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime? BussinessLogDate { get; set; }

        [Display(Name ="员工数量")]
        public List<CompanyBusinessDailyParam> EmployeeList { get; set; }
        [Display(Name = "软件系统(1有)")]
        public List<CompanyBusinessDailyParam> ItSystemList { get; set; }
        [Display(Name = "业务结构(张/天)")]
        public List<CompanyBusinessDailyParam> BusinessAmountList { get; set; }
        [Display(Name = "新业务量(单/天)")]
        public List<CompanyBusinessDailyParam> NewBusinessList { get; set; }
        [Display(Name = "照片")]
        public List<CompanyBusinessDailyPhoto> PhotoList { get; set; }
        [Display(Name = "录音")]
        public List<CompanyBusinessDailySoundRecord> SoundRecordList { get; set; }

        public CompanyBusinessDailyViewModel()
        {

        }

        public CompanyBusinessDailyViewModel(CompanyBusinessDaily daily,List<CompanyBusinessDailyParam> paramItems,List<CompanyBusinessDailyPhoto> photos,List<CompanyBusinessDailySoundRecord> sounds)
        {
            this.Id = daily.Id;
            this.CompanyId = daily.CompanyId;
            this.CompanyName = daily.CompanyName;
            this.CreateUserName = daily.CreateUserName;
            this.CreateTime = daily.CreateTime;
            this.ManagerName = daily.ManagerName;
            this.BussinessLogDate = daily.BussinessLogDate;
            this.BussinessType = daily.BussinessType;
           
            this.EmployeeList = new List<CompanyBusinessDailyParam>();
            this.ItSystemList = new List<CompanyBusinessDailyParam>();
            this.BusinessAmountList = new List<CompanyBusinessDailyParam>();
            this.NewBusinessList = new List<CompanyBusinessDailyParam>();
            this.PhotoList = photos;
            this.SoundRecordList = sounds;

            foreach (CompanyBusinessDailyParam item in paramItems)
            {
                switch (item.ParamName)
                {
                    case "员工数量":
                        this.EmployeeList.Add(item);
                        break;
                    case "业务结构":
                        this.BusinessAmountList.Add(item);
                        break;
                    case "软件系统":
                        this.ItSystemList.Add(item);
                        break;
                    case "新业务量":
                        this.NewBusinessList.Add(item);
                        break;
                    default:
                        break;
                }
            }
        }
    }
    
}

CrmWebApp/Controllers/CompanyBusinessDailiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CrmWebApp.Models;
using System.Data.SqlClient;
using PagedList;

namespace CrmWebApp.Controllers
{
    public class CompanyBusinessDailiesController : Controller
    {
        private OtaCrmModel db = new OtaCrmModel();

        // GET: CompanyBusinessDailies
        [Authorize(Roles = "SalesDirector,OtaSales,AreaManager,Admin")]
        public ActionResult Index(int? companyId, int? page)
        {
            if (companyId.HasValue)
            {
                ViewBag.CompanyId = companyId.Value;
                ViewBag.CompanyName = db.OtaCompany.FirstOrDefault(p => p.Id == companyId.Value).CompanyName;

                var model = from cbd in db.CompanyBusinessDaily
                            where cbd.CompanyId == companyId.Value
                            orderby cbd.Id descending
                            select cbd;
                int pageSize = 10;
                int pageNumber = (page ?? 1);

                return View(model.ToPagedList(pageNumber, pageSize));
            }
            return View();
        }
        [Authorize(Roles = "SalesDirector,OtaSales,AreaManager,Admin")]
        public ActionResult ShowViewPartial(int companyBusinessDailyId)
        {
            CompanyBusinessDaily dailyItem = db.CompanyBusinessDaily.FirstOrDefault(p => p.Id == companyBusinessDailyId);
            var paramList = from p in db.CompanyBusinessDailyParam
                            where p.CompanyBusinessDailyId == companyBusinessDailyId
                            select p;
            var photoList = from p in db.CompanyBusinessDailyPhoto
                            where p.CompanyBusinessDailyId == companyBusinessDailyId
                            select p;
            var soundList = from p in db.CompanyBusinessDailySoundRecord
                            where p.CompanyBusinessDailyId == companyBusinessDailyId
                            select p;
            var model = new CompanyBusinessDailyViewModel(dailyItem, paramList.ToList(), photoList.ToList(), soundList.ToList());
            return PartialView("_PartialCompanyBusinessDailyView", model);
        }

        // GET: CompanyBusinessDailies/Details/5
        [Authorize(Roles = "SalesDirector,OtaSales,AreaManager,Admin")]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyBusinessDaily companyBusinessDaily = await db.CompanyBusinessDaily.FindAsync(id);
            if (companyBusinessDaily == null)
            {
                return HttpNotFound();
            }
            var paramList = from p in db.CompanyBusinessDailyParam
                            where p.CompanyBusinessDailyId == id.Value
                            select p;
            var photoList = from p in db.CompanyBusinessDailyPhoto
                            where p.CompanyBusinessDailyId == id.Value
                            select p;
            var soundList = from p in db.CompanyBusinessDailySoundRecord
                            where p.CompanyBusinessDailyId == id.Value
                            select p;
            var model = new CompanyBusinessDailyViewModel(companyBusinessDaily, paramList.ToList(), photoList.ToList(), soundList.ToList());
            ViewBag.CompanyId = companyBusinessDaily.CompanyId;
            ViewBag.CompanyName = companyBusinessDaily.CompanyName;
            return View(model);
        }

        // GET: CompanyBusinessDailies/Create
        [Authorize(Roles = "SalesDirector,OtaSales,AreaManager,Admin")]
        public ActionResult Create(int? companyId)
        {
            var model = new CompanyBusinessDaily();
            if (companyId.HasValue)
            {
                model.CompanyId = companyId.Value;
                var company = db.OtaCompany.FirstOrDefault(p => p.Id == companyId.Value);
                if (company != null)
                {
                    model.CompanyName = company.CompanyName;
                }
                model.CreateUserName = User.Identity.Name;
                model.BussinessLogDate = DateTime.Today;
                model.CreateTime = DateTime.Now;
                model.ManagerName = ""; //取上一个记录得数据
                model.BussinessType = ""; //取上一个记录得数据
            }
            ViewData["BussinessTypeList"] = GetBussinessTypeList("国内");
            return View(model);
        }

        private List<SelectListItem> GetBussinessTypeList(string defaultValue)
        {
            var bussinessTypes = from p in db.ParamDict
                                 where p.ParamName == "业务类型"
                                 select p;
            List<SelectListItem> result = new List<SelectListItem>();
            foreach (var item in bussinessTypes)
            {
                SelectListItem selectItem = new SelectListItem();
                selectItem.Value = item.SubItemName;
                selectItem.Text = item.SubItemName;
                if (!string.IsNullOrEmpty(defaultValue) && defaultValue == item.SubItemName)
                {
                    selectItem.Selected = true;
                }
                result.Add(selectItem);
            }
            return result;
        }

        // POST: CompanyBusinessDailies/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "SalesDirector,OtaSales,AreaManager,Admin")]
        public async Task<ActionResult> Create([Bind(Include = "Id,CompanyId,CompanyName,BussinessType,ManagerName,CreateUserName,CreateTime,BussinessLogDate")] CompanyBusinessDaily companyBusinessDaily)
        {
            if (ModelState.IsValid)
            {
                db.CompanyBusinessDaily.Add(companyBusinessDaily);
                await db.SaveChangesAsync();
                return RedirectToAction("Edit", new { id = companyBusinessDaily.Id });
            }

            return View(companyBusinessDaily);
        }

        // GET: CompanyBusinessDailies/Edit/5
        [Authorize(Roles = "SalesDirector,OtaSales,AreaManager,Admin")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyBusinessDaily companyBusinessDaily = await db.CompanyBusinessDaily.FindAsync(id);
            if (companyBusinessDaily == null)
            {
                return HttpNotFound();
            }

            var paramList = from p in db.CompanyBusinessDailyParam
                            where p.CompanyBusinessDailyId == id.Value
                            select p;

            var photoList = from p in db.CompanyBusinessDailyPhoto
                            where p.CompanyBusinessDailyId == id.Value
                            select p;
            var soundList = from p in db.CompanyBusinessDailySoundRecord
                            where p.CompanyBusinessDailyId == id.Value
                            select p;
            var model = new CompanyBusinessDailyViewModel(companyBusinessDaily, paramList.ToList(), photoList.ToList(), soundList.ToList());
            //如果没有默认值，就需要赋值默认值
            if (model.BusinessAmountList == null || model.BusinessAmountList.Count == 0)
            {
                model.BusinessAmountList = GetDefaultDailyParamList(id.Value, "业务结构");
            }
            if (model.EmployeeList == null || model.EmployeeList.Count == 0)
            {
                model.EmployeeList = GetDefaultDailyParamList(id.Value, "员工数量");
            }
            if (model.NewBusinessList == null || model.NewBusinessList.Count == 0)
            {
                model.NewBusinessList = GetDefaultDailyParamList(id.Value, "新业务量");
            }
            if (model.ItSystemList == null || model.ItSystemList.Count == 0)
            {
                model.ItSystemList = GetDefaultDailyParamList(id.Value, "软件系统");
            }

            ViewData["BussinessTypeList"] = GetBussinessTypeList(companyBusinessDaily.BussinessType);

            return View(model);
        }

        public List<CompanyBusinessDailyParam> GetDefaultDailyParamList(int dailyId, string paramName)
        {
            //从字典表里面读取并赋值
            List<CompanyBusinessDailyParam> result = new List<Models.CompanyBusinessDailyParam>();
            var paramDicts = from p in db.ParamDict
                             where p.ParamName == paramName
                             select p;
            foreach (ParamDict paramDict in paramDicts)
            {
                CompanyBusinessDailyParam companyBusinessDailyParam = new CompanyBusinessDailyParam();
                companyBusinessDailyParam.CompanyBusinessDailyId = dailyId;
                companyBusinessDailyParam.Id = 0;
                companyBusinessDailyParam.ParamName = paramName;
                companyBusinessDailyParam.SubParamItem = paramDict.SubItemName;
                companyBusinessDailyParam.ItemAmount = 0;

                result.Add(companyBusinessDailyParam);
            }
            return result;
        }

        // POST: CompanyBusinessDailies/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "SalesDirector,OtaSales,AreaManager,Admin")]
        public async Task<ActionResult> Edit(CompanyBusinessDailyViewModel model, List<CompanyBusinessDailyParam> employeeList, List<CompanyBusinessDailyParam> businessAmountList,

CrmWebApp/Views/CompanyBusinessDailies/Create.cshtml
@model CrmWebApp.Models.CompanyBusinessDaily

@{
    ViewBag.Title = "Create";
}

<div class="row-fluid">
    <div class="span12">
        <ul class="breadcrumb">
            <li>
                <a href="~/Home/Index">主页</a> <span class="divider"></span>
            </li>
            <li>
                <a href="~/OtaCompanies/Index">公司</a> <span class="divider"></span>
            </li>
            <li>
                <a href="~/OtaCompanies/Details?id=@Model.CompanyId">@Model.CompanyName</a><span class="divider"></span>
            </li>
            <li>
                <a href="~/CompanyBusinessDailies/Index?companyId=@Model.CompanyId">运营</a> <span class="divider"></span>
            </li>
            <li>
                <a href="#">新增</a> <span class="divider"></span>
            </li>
        </ul>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.CompanyId)
        @Html.HiddenFor(model => model.CompanyName)
        <div class="form-group">
            @Html.LabelFor(model => model.BussinessType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.BussinessType, ViewData["BussinessTypeList"] as List<SelectListItem>, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BussinessType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ManagerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ManagerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ManagerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BussinessLogDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BussinessLogDate, new { htmlAttributes = new { @class = "form-control datetimepicker" } })
                @Html.ValidationMessageFor(model => model.BussinessLogDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateUserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateUserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreateUserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateTime, new { htmlAttributes = new { @class = "form-control datetimepicker" } })
                @Html.ValidationMessageFor(model => model.CreateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="新增" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("返回列表", "Index", new { companyId = Model.CompanyId })
</div>

<script type="text/javascript">
    $(".datetimepicker").datetimepicker({
        format: "YYYY-MM-DD"
    });
</script>

CrmWebApp/Views/CompanyBusinessDailies/Delete.cshtml
@model CrmWebApp.Models.CompanyBusinessDaily

@{
    ViewBag.Title = "Delete";
}

<div class="row-fluid">
    <div class="span12">
        <ul class="breadcrumb">
            <li>
                <a href="~/Home/Index">主页</a> <span class="divider"></span>
            </li>
            <li>
                <a href="~/OtaCompanies/Index">公司</a> <span class="divider"></span>
            </li>
            <li>
                <a href="~/OtaCompanies/Details?id=@Model.CompanyId">@Model.CompanyName</a><span class="divider"></span>
            </li>
            <li>
                <a href="~/CompanyBusinessDailies/Index?companyId=@Model.CompanyId">运营</a> <span class="divider"></span>
            </li>
            <li class="active">
                <a href="#">删除</a> <span class="divider"></span>
            </li>
        </ul>
    </div>
</div>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CompanyId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BussinessType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BussinessType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ManagerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ManagerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateUserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateUserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BussinessLogDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BussinessLogDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("返回列表", "Index", new { companyId = Model.CompanyId })
        </div>
    }
</div>

CrmWebApp/Views/CompanyBusinessDailies/Details.cshtml
@model CrmWebApp.Models.CompanyBusinessDailyViewModel

@{
    ViewBag.Title = "Details";
}
<div class="row-fluid">
    <div class="span12">
        <ul class="breadcrumb">
            <li>
                <a href="~/Home/Index">主页</a> <span class="divider"></span>
            </li>
            <li>
                <a href="~/OtaCompanies/Index">公司</a> <span class="divider"></span>
            </li>
            <li class="active">
                <a href="~/OtaCompanies/Details?id=@Model.CompanyId">@Model.CompanyName</a><span class="divider"></span>
            </li>
            <li>
                <a href="~/CompanyBusinessDailies/Index?companyId=@Model.CompanyId">运营</a> <span class="divider"></span>
            </li>
            <li>
                <a href="#">详情</a> <span class="divider"></span>
            </li>
        </ul>
    </div>
</div>

<div class="container-fluid">
    <div class="row-fluid">
        <hr />
        <table>
            <tr>
                <td>
                    <h4>@Html.DisplayNameFor(model => model.CompanyName)</h4>
                </td>
                <td>
                    @Html.DisplayFor(model => model.CompanyName)
                </td>
            </tr>
            <tr>
                <td>
                    <h4>@Html.DisplayNameFor(model => model.BussinessType)</h4>
                </td>
                <td>
                    @Html.DisplayFor(model => model.BussinessType)
                </td>
            </tr>
            <tr>
                <td>
                    <h4>@Html.DisplayNameFor(model => model.ManagerName)</h4>
                </td>
                <td>
                    @Html.DisplayFor(model => model.ManagerName)
                </td>
            </tr>
            <tr>
                <td>
                    <h4>@Html.DisplayNameFor(model => model.CreateUserName)</h4>
                </td>
                <td>
                    @Html.DisplayFor(model => model.CreateUserName)
                </td>
            </tr>
            <tr>
                <td>
                    <h4>@Html.DisplayNameFor(model => model.CreateTime)</h4>
                </td>
                <td>
                    @Html.DisplayFor(model => model.CreateTime)
                </td>
            </tr>
            <tr>
                <td>
                    <h4>@Html.DisplayNameFor(model => model.BussinessLogDate)</h4>
                </td>
                <td>
                    @Html.DisplayFor(model => model.BussinessLogDate)
                </td>
            </tr>
            <tr>
                <td>
                    <h4>员工数</h4>
                </td>
                <td>
                    <a href="#" class="glyphicon glyphicon-plus"></a>
                    @Html.Partial("_PartialBusinessParamListView", Model.EmployeeList)
                </td>
            </tr>
            <tr>
                <td>
                    <h4>软件系统</h4>
                </td>
                <td></td>
            </tr>
            <tr>
                <td>
                    <h4>业务结构</h4>
                </td>
                <td></td>
            </tr>
            <tr>
                <td>
                    <h4>新业务</h4>
                </td>
                <td></td>
            </tr>
            <tr>
                <td>
                    <h4>照片</h4>
                </td>
                <td></td>
            </tr>
            <tr>
                <td>
                    <h4>录音</h4>
                </td>
                <td></td>
            </tr>
        </table>
    </div>
</div>
<p>
    @Html.ActionLink("编辑", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("返回列表", "Index", new { companyId = Model.CompanyId })
</p>

CrmWebApp/Views/CompanyBusinessDailies/Index.cshtml
@model PagedList.IPagedList<CrmWebApp.Models.CompanyBusinessDaily>
@using PagedList.Mvc;

@{
    ViewBag.Title = "运营情况-" + ViewBag.CompanyName;
}

<div class="row-fluid">
    <div class="span12">
        <ul class="breadcrumb">
            <li>
                <a href="~/Home/Index">主页</a><span class="divider"></span>
            </li>
            <li>
                <a href="~/OtaCompanies/Index">公司</a><span class="divider"></span>
            </li>
            <li>
                <a href="~/OtaCompanies/Details?id=@ViewBag.CompanyId">@ViewBag.CompanyName</a><span class="divider"></span>
            </li>
            <li>
                <a href="#">运营</a><span class="divider"></span>
            </li>
        </ul>
    </div>
</div>
<p>
    @Html.ActionLink("新建", "Create", "CompanyBusinessDailies", new { companyId = ViewBag.CompanyId }, new { @class = "btn btn-default" })
</p>
<table class="table">
    <tr>
        <th>
            类型
        </th>
        <th>
            主管
        </th>
        <th>
            运营日期
        </th>
        <th>
            录入人
        </th>
        <th>
            录入时间
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BussinessType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ManagerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BussinessLogDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreateUserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreateTime)
            </td>

            <td>
                <a href="#" class="btn btn-default" data-toggle="modal" data-target="#modalDiv" onclick="ShowModalDiv('@item.Id')">查看</a>
                @Html.ActionLink("修改", "Edit", new { id = item.Id }, new { @class = "btn btn-default" })
                @Html.ActionLink("删除", "Delete", new { id = item.Id }, new { @class = "btn btn-default" })
            </td>
        </tr>
    }

</table>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, companyId = ViewBag.CompanyId }))


<div class="modal" id="modalDiv" tabindex="-1" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <a href="#" class="close" data-dismiss="modal">&times;</a>
            </div>
            <div class="modal-body" id="modalBodyDiv">
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-default" data-dismiss="modal">关闭</a>
            </div>
        </div>
    </div>
</div>




<script>

    var ShowModalDiv = function (modelParam) {
        var serverUrl = "@Url.Content("~/")";
        var url = serverUrl + "CompanyBusinessDailies/ShowViewPartial?companyBusinessDailyId=" + modelParam;
        $("#modalBodyDiv").load(url, function () {
            $("#modalDiv").modal("show");
        })
    }
</script>